// <auto-generated />
using LoyaltyCardManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyCardManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("LoyaltyCardManager.Core.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fast Food and casual Dining",
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Airlines, railways companies",
                            Name = "Transports"
                        });
                });

            modelBuilder.Entity("LoyaltyCardManager.Core.Entities.LoyaltyCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("loyaltyCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MembershipId = "0035595443",
                            MerchantName = "Los pollos hermanos"
                        },
                        new
                        {
                            Id = 2,
                            MembershipId = "2178445",
                            MerchantName = "Big Kahuna burger"
                        },
                        new
                        {
                            Id = 3,
                            MembershipId = "6259663200",
                            MerchantName = "Oceanic Airlines"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
