// <auto-generated />
using System;
using DotnetSampleSolution.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetSampleSolution.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("DotnetSampleSolution.Core.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Formats the information provided by a website or an application through a set of contents",
                            Name = "Design team"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Responsible for all the work required to create functional and quality software.",
                            Name = "Development team"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Works to promote products and services on the Internet",
                            Name = "SEO & marketing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Accountable for the sound financial, accounting, and budgetary management of the programs, and the management of human resources and administrative / legal records",
                            Name = "Finance/HR/Admin"
                        });
                });

            modelBuilder.Entity("DotnetSampleSolution.Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1989, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.wilson@company.tld",
                            FirstName = "Michael",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1979, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jerry.whitehall@company.tld",
                            FirstName = "Jerry",
                            LastName = "Whitehall"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1984, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter.parvin@company.tld",
                            FirstName = "Peter",
                            LastName = "Parvin"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1989, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mary.reed@company.tld",
                            FirstName = "Mary",
                            LastName = "Reed"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1990, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucy.estevez@company.tld",
                            FirstName = "Ducy",
                            LastName = "Estevez"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1985, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "donna.archer@company.tld",
                            FirstName = "Donna",
                            LastName = "Archer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
